services:
  ba-skolekube:
    container_name: ba-skolekube
    # image: 'ghcr.io/hjk-automatisering/ba-skolekube:main' # Uncomment on portainer
    build: . # Remove on portainer
    volumes:
      - filer-istskole360:/shr/ISTSkole360
    env_file:
      - .env # stack.env on portainer
    restart: on-failure
    environment:
      - TZ=Europe/Copenhagen
volumes:
  filer-istskole360:
    external: true